#!/usr/bin/env bash
# Bash script that will display information about subdomains.
# Bash script must accept 2 arguments:
# domain: (type: string, what: domain name to audit, mandatory: yes)
# subdomain: (type: string, what: specific subdomain to audit, mandatory: no)
# Output: The subdomain [SUB_DOMAIN] is a
# [RECORD_TYPE] record and points to [DESTINATION]
# When only the parameter domain is provided, display information for its
# subdomains: www, lb-01, web-01 and web-02 - in this specific order
# passing domain and subdomain, display information for specified subdomain
if [ "$#" = "2" ]; then
    echo -n "The subdomain $2 "
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{print "is a " $4 " record and points to " $5}'
else
    LIST=("www" "lb-01" "web-01" "web-02")
    for i in "${LIST[@]}"
    do
        echo -n "The subdomain $i "
        dig "$i.$1" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{print "is a " $4 " record and points to " $5}'
    done
fi