#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine
# install nginx on your web-01 server
# Nginx should be listening on port 80
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
service nginx start