#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404
# page that contains the string Ceci n'est pas une page.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
service nginx start
new_string="location /redirect_me {\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}\n"
sudo sed -i "43i $new_string" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
error_page="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /var/www/html;\ninternal;\n}\n"
sudo sed -i "20i $error_page" /etc/nginx/sites-available/default
sudo service nginx restart