#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine
# with haproxy balancer
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
sudo sed -i "s\ENABLED=0/ENABLED=1/g" /etc/default/haproxy
sudo sed -i "\$ a\frontend haproxy\n\tbind *:80\n\tmode http\n\tdefault_backend WEBSERVERS\n\nbackend WEBSERVERS\n\tbalance roundrobin\n\tserver web1 35.229.126.169:80 check\n\tserver web2 54.90.172.156:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
