#!/usr/bin/env bash
# script that generates a MySQL dump and creates
# a compressed archive out of it.
mysqldump -u root -p "$1" --opt --databases > backup.sql
tar -zcvf "$(date '+%d-%m-%Y').tar.gz" backup.sql