#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s
# Nginx installation from listening on port 80
sudo sed -i "s\listen 8080 default_server;/listen 80 default_server;/g" /etc/nginx/sites-enabled/default
sudo sed -i "s\listen [::]:8080 default_server ipv6only=on;/listen [::]:80 default_server ipv6only=on;/g" /etc/nginx/sites-enabled/defaultlisten [::]:80 default_server ipv6only=on;
sudo service nginx start
