#!/usr/bin/env bash
# Bash script that:
# Creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself 
# when receiving a SIGQUIT or SIGTERM signal

sudo mkdir /var/run/
echo $$ > /var/run/holbertonscript.pid
