#!/usr/bin/env bash
# Using your previous exercise command, write a Bash script that displays lines
# containing the bash word, thus allowing you to easily get the PID of your Bash process.
# You cannot use pgrep
# The third line of your script must be # shellcheck disable=SC2009

# shellcheck disable=SC2009

ps -auxf | grep bash
