#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
# script should only display:
# username
# user id
# Home directory path for the user

while IFS= read
do
    cut -d ":" -f 1,3,6
done < /etc/passwd
