#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd
# using the while loop + IFS.

while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
    printf "The user %s is part of the %s gang, lives in %s and rides %s. %s place is protected by the passcode %s, more info about the user here: %s\n" "$f1" "$f4" "$f6" "$f7" "$f3" "$f2" "$f5"
done < /etc/passwd
