#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times but after nine print Hi

i=1
j=9
while ((i < 11))
do
	echo "Holberton School"
	if [ "$i" = "$j" ]; then
		echo "Hi"
	fi
	((i++))
done
