#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times but after nine print Hi

i=1
while ((i < 11))
do
	if [ "$i" = "4" ]; then
		echo "bad luck"
	elif [ "$i" = "8" ]; then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((i++))
done
