#!/usr/bin/env bash
# Bash script that gives you information about the holbertonschool file

new_file=./holbertonschool
if [ -e "$new_file" ]; then
	echo "holbertonschool file exists"
	if [ ! -s "$new_file" ]; then
		echo "holbertonschool file is empty"
	else	
		echo "holbertonschool file is not empty"
	fi
	if [ -f "$new_file" ]; then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
